test

diff --git a/launcher/command-chain/desktop-launch6 b/launcher/command-chain/desktop-launch6
--- a/launcher/command-chain/desktop-launch6
+++ b/launcher/command-chain/desktop-launch6
@@ -73,12 +73,14 @@ else
   ARCH="$SNAP_ARCH-linux-gnu"
 fi
 
-export SNAP_LAUNCHE R_ARCH_TRIPLET="$ARCH"
+export SNAP_LAUNCHER_ARCH_TRIPLET="$ARCH"
 
 # Don't LD_PRELOAD bindtextdomain for classic snaps
 if ! grep -qs "^\s*confinement:\s*classic\s*" "$SNAP/meta/snap.yaml"; then
   if [ -f "$SNAP/lib/$ARCH/bindtextdomain.so" ]; then
     export LD_PRELOAD="$LD_PRELOAD:$SNAP/\$LIB/bindtextdomain.so"
+  elif [ -f "$SNAP/kde-qt6-core24/lib/$ARCH/bindtextdomain.so" ] && ! grep -qs "^\s*default-provider:\s*wine-platform-runtime*" "$SNAP/meta/snap.yaml"; then
+    export LD_PRELOAD="$LD_PRELOAD:$SNAP/kde-qt6-core24/\$LIB/bindtextdomain.so"
   fi
 fi
 ###############################################
@@ -142,22 +144,27 @@ function is_subpath() {
   [ "${dir##"${parent}"/}" != "${dir}" ] && return 0 || return 1
 }
 
+if ! snapctl is-connected "kf6-core24"; then
+  echo "ERROR: not connected to the kf6-core24 content interface."
+  exit 1
+fi
+
 # Use keyfile storage if gsettings isn't accessible
 if ! snapctl is-connected gsettings 2>/dev/null; then
   export GSETTINGS_BACKEND=keyfile
 fi
 
-append_dir LD_LIBRARY_PATH "$SNAP/lib/$ARCH"
-append_dir LD_LIBRARY_PATH "$SNAP/usr/lib/$ARCH"
-append_dir LD_LIBRARY_PATH "$SNAP/usr/lib"
-append_dir LD_LIBRARY_PATH "$SNAP/lib"
-append_dir PATH "$SNAP/usr/bin"
+append_dir LD_LIBRARY_PATH "$SNAP_DESKTOP_RUNTIME/lib/$ARCH"
+append_dir LD_LIBRARY_PATH "$SNAP_DESKTOP_RUNTIME/usr/lib/$ARCH"
+append_dir LD_LIBRARY_PATH "$SNAP_DESKTOP_RUNTIME/usr/lib"
+append_dir LD_LIBRARY_PATH "$SNAP_DESKTOP_RUNTIME/lib"
+append_dir PATH "$SNAP_DESKTOP_RUNTIME/usr/bin"
 
 # XKB config
-export XKB_CONFIG_ROOT="$SNAP/usr/share/X11/xkb"
+export XKB_CONFIG_ROOT="$SNAP_DESKTOP_RUNTIME/usr/share/X11/xkb"
 
 # Set XCursors path
-export XCURSOR_PATH="$SNAP/usr/share/icons"
+export XCURSOR_PATH="$SNAP_DESKTOP_RUNTIME/usr/share/icons"
 prepend_dir XCURSOR_PATH "$SNAP/data-dir/icons"
 
 # Unless told to defer to the gpu interface
@@ -165,16 +172,16 @@ prepend_dir XCURSOR_PATH "$SNAP/data-dir/icons"
 if [ "false" != "false" ]; then
   # Give XOpenIM a chance to locate locale data.
   # This is required for text input to work in SDL2 games.
-  export XLOCALEDIR="$SNAP/usr/share/X11/locale"
+  export XLOCALEDIR="$SNAP_DESKTOP_RUNTIME/usr/share/X11/locale"
 
   # Mesa Libs for OpenGL support
-  append_dir LD_LIBRARY_PATH "$SNAP/usr/lib/$ARCH/mesa"
-  append_dir LD_LIBRARY_PATH "$SNAP/usr/lib/$ARCH/mesa-egl"
+  append_dir LD_LIBRARY_PATH "$SNAP_DESKTOP_RUNTIME/usr/lib/$ARCH/mesa"
+  append_dir LD_LIBRARY_PATH "$SNAP_DESKTOP_RUNTIME/usr/lib/$ARCH/mesa-egl"
 
   # Tell libGL and libva where to find the drivers
-  export LIBGL_DRIVERS_PATH="$SNAP/usr/lib/$ARCH/dri"
+  export LIBGL_DRIVERS_PATH="$SNAP_DESKTOP_RUNTIME/usr/lib/$ARCH/dri"
   append_dir LD_LIBRARY_PATH "$LIBGL_DRIVERS_PATH"
-  append_dir LIBVA_DRIVERS_PATH "$SNAP/usr/lib/$ARCH/dri"
+  append_dir LIBVA_DRIVERS_PATH "$SNAP_DESKTOP_RUNTIME/usr/lib/$ARCH/dri"
 
   # Set where the VDPAU drivers are located
   export VDPAU_DRIVER_PATH="/usr/lib/$ARCH/vdpau/"
@@ -196,36 +203,36 @@ if [ "false" != "false" ]; then
 
   # EGL vendor files on glvnd enabled systems
   prepend_dir __EGL_VENDOR_LIBRARY_DIRS "/var/lib/snapd/lib/glvnd/egl_vendor.d"
-  append_dir __EGL_VENDOR_LIBRARY_DIRS "$SNAP/usr/share/glvnd/egl_vendor.d"
+  append_dir __EGL_VENDOR_LIBRARY_DIRS "$SNAP_DESKTOP_RUNTIME/usr/share/glvnd/egl_vendor.d"
 fi
 
 # Unity7 export (workaround for https://launchpad.net/bugs/1638405)
-append_dir LD_LIBRARY_PATH "$SNAP/usr/lib/$ARCH/libunity"
+append_dir LD_LIBRARY_PATH "$SNAP_DESKTOP_RUNTIME/usr/lib/$ARCH/libunity"
 
 # Pulseaudio export
-append_dir LD_LIBRARY_PATH "$SNAP/usr/lib/$ARCH/pulseaudio"
+append_dir LD_LIBRARY_PATH "$SNAP_DESKTOP_RUNTIME/usr/lib/$ARCH/pulseaudio"
 
 # Tell Pipewire where to find its configuration and plugins
-export PIPEWIRE_CONFIG_DIR="$SNAP/usr/share/pipewire"
-export PIPEWIRE_MODULE_DIR="$SNAP/usr/lib/$ARCH/pipewire-0.3"
-export SPA_PLUGIN_DIR="$SNAP/usr/lib/$ARCH/spa-0.2"
+export PIPEWIRE_CONFIG_DIR="$SNAP_DESKTOP_RUNTIME/usr/share/pipewire"
+export PIPEWIRE_MODULE_DIR="$SNAP_DESKTOP_RUNTIME/usr/lib/$ARCH/pipewire-0.3"
+export SPA_PLUGIN_DIR="$SNAP_DESKTOP_RUNTIME/usr/lib/$ARCH/spa-0.2"
 
 # Tell GStreamer where to find its plugins
 export GST_PLUGIN_PATH="$SNAP/usr/lib/$ARCH/gstreamer-1.0"
-export GST_PLUGIN_SYSTEM_PATH="$SNAP/usr/lib/$ARCH/gstreamer-1.0"
+export GST_PLUGIN_SYSTEM_PATH="$SNAP_DESKTOP_RUNTIME/usr/lib/$ARCH/gstreamer-1.0"
 # gst plugin scanner doesn't install in the correct path: https://github.com/ubuntu/snapcraft-desktop-helpers/issues/43
-export GST_PLUGIN_SCANNER="$SNAP/usr/lib/$ARCH/gstreamer1.0/gstreamer-1.0/gst-plugin-scanner"
+export GST_PLUGIN_SCANNER="$SNAP_DESKTOP_RUNTIME/usr/lib/$ARCH/gstreamer1.0/gstreamer-1.0/gst-plugin-scanner"
 
 # XDG Config
 # KConfig uses QStandardPaths:GenericConfigLocation to get the config dir paths
 # and checks for the kdeglobals file there for theming. The kdeglobals file is
 # stored in $SNAP_REAL_HOME/.config folder.
 prepend_dir XDG_CONFIG_DIRS "$SNAP_REAL_HOME/.config"
-prepend_dir XDG_CONFIG_DIRS "$SNAP/etc/xdg"
+prepend_dir XDG_CONFIG_DIRS "$SNAP_DESKTOP_RUNTIME/etc/xdg"
 prepend_dir XDG_CONFIG_DIRS "$SNAP/etc/xdg"
 
 # Define snaps' own data dir
-prepend_dir XDG_DATA_DIRS "$SNAP/usr/share"
+prepend_dir XDG_DATA_DIRS "$SNAP_DESKTOP_RUNTIME/usr/share"
 prepend_dir XDG_DATA_DIRS "$SNAP/usr/share"
 prepend_dir XDG_DATA_DIRS "$SNAP/share"
 prepend_dir XDG_DATA_DIRS "$SNAP/data-dir"
@@ -252,7 +259,7 @@ ensure_dir_exists "$XDG_CACHE_HOME"
 ensure_dir_exists "$XDG_RUNTIME_DIR" -m 700
 
 # Ensure the app finds locale definitions (requires locales-all to be installed)
-append_dir LOCPATH "$SNAP/usr/lib/locale"
+append_dir LOCPATH "$SNAP_DESKTOP_RUNTIME/usr/lib/locale"
 
 # If any, keep track of where XDG dirs were so we can potentially migrate the content later
 update_xdg_dirs_values
@@ -376,9 +383,9 @@ if [ -n "$XDG_RUNTIME_DIR" ]; then
 fi
 
 # GI repository
-prepend_dir GI_TYPELIB_PATH "$SNAP/usr/lib/$ARCH/girepository-1.0"
-prepend_dir GI_TYPELIB_PATH "$SNAP/usr/lib/girepository-1.0"
-prepend_dir GI_TYPELIB_PATH "$SNAP/usr/lib/gjs/girepository-1.0"
+prepend_dir GI_TYPELIB_PATH "$SNAP_DESKTOP_RUNTIME/usr/lib/$ARCH/girepository-1.0"
+prepend_dir GI_TYPELIB_PATH "$SNAP_DESKTOP_RUNTIME/usr/lib/girepository-1.0"
+prepend_dir GI_TYPELIB_PATH "$SNAP_DESKTOP_RUNTIME/usr/lib/gjs/girepository-1.0"
 prepend_dir GI_TYPELIB_PATH "$SNAP/usr/lib/$ARCH/girepository-1.0"
 prepend_dir GI_TYPELIB_PATH "$SNAP/usr/lib/girepository-1.0"
 prepend_dir GI_TYPELIB_PATH "$SNAP/usr/lib/gjs/girepository-1.0"
@@ -387,8 +394,8 @@ prepend_dir GI_TYPELIB_PATH "$SNAP/usr/lib/gjs/girepository-1.0"
 IFS=':' read -r -a data_dirs_array <<< "$XDG_DATA_DIRS"
 
 # Font Config and themes
-export FONTCONFIG_PATH="$SNAP/etc/fonts"
-export FONTCONFIG_FILE="$SNAP/etc/fonts/fonts.conf"
+export FONTCONFIG_PATH="$SNAP_DESKTOP_RUNTIME/etc/fonts"
+export FONTCONFIG_FILE="$SNAP_DESKTOP_RUNTIME/etc/fonts/fonts.conf"
 
 function make_user_fontconfig {
   echo "<fontconfig>"
@@ -432,9 +439,9 @@ if [ "$needs_update" = true ]; then
   if [ -d "$SNAP/data-dir/themes" ]; then
     ln -sf "$SNAP/data-dir/themes" "$XDG_DATA_HOME"
     ln -sfn "$SNAP/data-dir/themes" "$SNAP_USER_DATA/.themes"
-  elif [ -d "$SNAP/usr/share/themes" ]; then
-    ln -sf "$SNAP/usr/share/themes" "$XDG_DATA_HOME"
-    ln -sfn "$SNAP/usr/share/themes" "$SNAP_USER_DATA/.themes"
+  elif [ -d "$SNAP_DESKTOP_RUNTIME/usr/share/themes" ]; then
+    ln -sf "$SNAP_DESKTOP_RUNTIME/usr/share/themes" "$XDG_DATA_HOME"
+    ln -sfn "$SNAP_DESKTOP_RUNTIME/usr/share/themes" "$SNAP_USER_DATA/.themes"
   fi
 fi
 
@@ -442,9 +449,9 @@ fi
 # needed for gtk and qt icon
 if [ "$needs_update" = true ]; then
   rm -rf "$XDG_DATA_HOME/mime"
-  if [ ! -f "$SNAP/usr/share/mime/mime.cache" ]; then
+  if [ ! -f "$SNAP_DESKTOP_RUNTIME/usr/share/mime/mime.cache" ]; then
     if command -v update-mime-database >/dev/null; then
-      cp --preserve=timestamps -dR "$SNAP/usr/share/mime" "$XDG_DATA_HOME"
+      cp --preserve=timestamps -dR "$SNAP_DESKTOP_RUNTIME/usr/share/mime" "$XDG_DATA_HOME"
       async_exec update-mime-database "$XDG_DATA_HOME/mime"
     fi
   fi
@@ -476,7 +483,7 @@ function compile_schemas {
   fi
 }
 if [ "$needs_update" = true ]; then
-  async_exec compile_schemas "$SNAP/usr/bin/glib-compile-schemas"
+  async_exec compile_schemas "$SNAP_DESKTOP_RUNTIME/usr/bin/glib-compile-schemas"
 fi
 
 # Enable gsettings user changes
@@ -501,11 +508,11 @@ append_dir LD_LIBRARY_PATH "$SNAP/testability/$ARCH/mesa"
 
 # Gdk-pixbuf loaders
 export GDK_PIXBUF_MODULE_FILE="$XDG_CACHE_HOME/gdk-pixbuf-loaders.cache"
-export GDK_PIXBUF_MODULEDIR="$SNAP/usr/lib/$ARCH/gdk-pixbuf-2.0/2.10.0/loaders"
+export GDK_PIXBUF_MODULEDIR="$SNAP_DESKTOP_RUNTIME/usr/lib/$ARCH/gdk-pixbuf-2.0/2.10.0/loaders"
 if [ "$needs_update" = true ] || [ ! -f "$GDK_PIXBUF_MODULE_FILE" ]; then
   rm -f "$GDK_PIXBUF_MODULE_FILE"
-  if [ -f "$SNAP/usr/lib/$ARCH/gdk-pixbuf-2.0/gdk-pixbuf-query-loaders" ]; then
-    async_exec "$SNAP/usr/lib/$ARCH/gdk-pixbuf-2.0/gdk-pixbuf-query-loaders" > "$GDK_PIXBUF_MODULE_FILE"
+  if [ -f "$SNAP_DESKTOP_RUNTIME/usr/lib/$ARCH/gdk-pixbuf-2.0/gdk-pixbuf-query-loaders" ]; then
+    async_exec "$SNAP_DESKTOP_RUNTIME/usr/lib/$ARCH/gdk-pixbuf-2.0/gdk-pixbuf-query-loaders" > "$GDK_PIXBUF_MODULE_FILE"
   fi
 fi
 
@@ -516,7 +523,7 @@ if [ "$needs_update" = true ]; then
   for ((i = 0; i < ${#data_dirs_array[@]}; i++)); do
     # The runtime and theme content snaps should already contain icon caches
     # so we skip them to optimise app start time.
-    if [[ "${data_dirs_array[$i]}" == "$SNAP/data-dir" || "${data_dirs_array[$i]}" == "$SNAP/"* ]]; then
+    if [[ "${data_dirs_array[$i]}" == "$SNAP/data-dir" || "${data_dirs_array[$i]}" == "$SNAP_DESKTOP_RUNTIME/"* ]]; then
       continue
     fi
     for theme in "${data_dirs_array[$i]}"/icons/*; do
@@ -525,10 +532,10 @@ if [ "$needs_update" = true ]; then
         if [ ! -d "$theme_dir" ]; then
           ensure_dir_exists "$theme_dir"
           ln -s "$theme"/* "$theme_dir"
-          if [ -f "$SNAP/usr/sbin/update-icon-caches" ]; then
-            async_exec "$SNAP/usr/sbin/update-icon-caches" "$theme_dir"
-          elif [ -f "$SNAP/usr/sbin/update-icon-cache.gtk2" ]; then
-            async_exec "$SNAP/usr/sbin/update-icon-cache.gtk2" "$theme_dir"
+          if [ -f "$SNAP_DESKTOP_RUNTIME/usr/sbin/update-icon-caches" ]; then
+            async_exec "$SNAP_DESKTOP_RUNTIME/usr/sbin/update-icon-caches" "$theme_dir"
+          elif [ -f "$SNAP_DESKTOP_RUNTIME/usr/sbin/update-icon-cache.gtk2" ]; then
+            async_exec "$SNAP_DESKTOP_RUNTIME/usr/sbin/update-icon-cache.gtk2" "$theme_dir"
           fi
         fi
       fi
@@ -555,53 +562,68 @@ ensure_dir_exists "$IBUS_CONFIG_PATH"
 ln -sfn "$SNAP_REAL_HOME/.config/ibus/bus" "$IBUS_CONFIG_PATH"
 
 # Set libgweather path
-export LIBGWEATHER_LOCATIONS_PATH="$SNAP/usr/lib/$ARCH/libgweather-4/Locations.bin"
+export LIBGWEATHER_LOCATIONS_PATH="$SNAP_DESKTOP_RUNTIME/usr/lib/$ARCH/libgweather-4/Locations.bin"
 
 # Set libthai dict path
-export LIBTHAI_DICTDIR="$SNAP/usr/share/libthai/"
+export LIBTHAI_DICTDIR="$SNAP_DESKTOP_RUNTIME/usr/share/libthai/"
 
 # Workaround for libproxy. It sets DT_RUNTIME to be able to find libpxbackend, which
 # isn't in the normal library path, but inside a folder. This works when the library
 # is in the default place, but not if it is snapped in the gnome-sdk/gnome-runtime snap.
 
-append_dir LD_LIBRARY_PATH "$SNAP/usr/lib/$ARCH/libproxy"
+append_dir LD_LIBRARY_PATH "$SNAP_DESKTOP_RUNTIME/usr/lib/$ARCH/libproxy"
+###################################
+# KDE NEON launcher specific part #
+###################################
 
 # Add paths for games
 append_dir PATH "$SNAP/usr/games"
-append_dir PATH "$SNAP/usr/games"
+append_dir PATH "$SNAP_DESKTOP_RUNTIME/usr/games"
 
 # Qt Libs
-prepend_dir LD_LIBRARY_PATH "$SNAP/usr/lib"
-prepend_dir LD_LIBRARY_PATH "$SNAP/usr/lib/$ARCH"
+prepend_dir LD_LIBRARY_PATH "$SNAP_DESKTOP_RUNTIME/usr/lib"
+prepend_dir LD_LIBRARY_PATH "$SNAP_DESKTOP_RUNTIME/usr/lib/$ARCH"
 
 # blas
-append_dir LD_LIBRARY_PATH "$SNAP/usr/lib/$ARCH/blas"
+append_dir LD_LIBRARY_PATH "$SNAP_DESKTOP_RUNTIME/usr/lib/$ARCH/blas"
 # lapack
-append_dir LD_LIBRARY_PATH "$SNAP/usr/lib/$ARCH/lapack"
+append_dir LD_LIBRARY_PATH "$SNAP_DESKTOP_RUNTIME/usr/lib/$ARCH/lapack"
 
 
 # Add QT_PLUGIN_PATH (Qt Modules).
 append_dir QT_PLUGIN_PATH "$SNAP/usr/lib/$ARCH/qt6/plugins"
 append_dir QT_PLUGIN_PATH "$SNAP/usr/lib/$ARCH/plugins"
 append_dir QT_PLUGIN_PATH "$SNAP/usr/lib/$ARCH"
-append_dir QT_PLUGIN_PATH "$SNAP/usr/lib/$ARCH/qt6/plugins"
-append_dir QT_PLUGIN_PATH "$SNAP/usr/lib/$ARCH/plugins"
-append_dir QT_PLUGIN_PATH "$SNAP/usr/lib/$ARCH/"
+append_dir QT_PLUGIN_PATH "$SNAP_DESKTOP_RUNTIME/usr/lib/$ARCH/qt6/plugins"
+append_dir QT_PLUGIN_PATH "$SNAP_DESKTOP_RUNTIME/usr/lib/$ARCH/plugins"
+append_dir QT_PLUGIN_PATH "$SNAP_DESKTOP_RUNTIME/usr/lib/$ARCH/"
 # And QML2_IMPORT_PATH (Qt Modules).
 append_dir QML2_IMPORT_PATH "$SNAP/usr/lib/$ARCH/qt6/qml"
-append_dir QML2_IMPORT_PATH "$SNAP/usr/lib/$ARCH/qt6/qml"
-append_dir QML2_IMPORT_PATH "$SNAP/usr/lib/$ARCH/qml"
+append_dir QML2_IMPORT_PATH "$SNAP_DESKTOP_RUNTIME/usr/lib/$ARCH/qt6/qml"
+append_dir QML2_IMPORT_PATH "$SNAP_DESKTOP_RUNTIME/usr/lib/$ARCH/qml"
+
+# Qt style breeze
+append_dir QT_STYLE_OVERRIDE "Breeze"
 
 # Fix locating the QtWebEngineProcess executable
-export QTWEBENGINEPROCESS_PATH="$SNAP/usr/lib/qt6/libexec/QtWebEngineProcess"
+export QTWEBENGINEPROCESS_PATH="$SNAP_DESKTOP_RUNTIME/usr/lib/qt6/libexec/QtWebEngineProcess"
 
 # Fix sound issues with many apps.
-export ALSA_CONFIG_PATH="$SNAP/etc/asound.conf"
+export ALSA_CONFIG_PATH="$SNAP_DESKTOP_RUNTIME/etc/asound.conf"
 
 # Removes Qt warning: Could not find a location
 # of the system Compose files
-export QTCOMPOSE="$SNAP/usr/share/X11/locale"
-export QT_XKB_CONFIG_ROOT="/usr/share/X11/xkb"
+export QTCOMPOSE="$SNAP_DESKTOP_RUNTIME/usr/share/X11/locale"
+export QT_XKB_CONFIG_ROOT="$SNAP_DESKTOP_RUNTIME/usr/share/X11/xkb"
+
+# KIO specific
+# Directly fork slaves.
+export KDE_FORK_SLAVES=1
+# Path to KIO slaves.
+export KF6_LIBEXEC_DIR="$SNAP_DESKTOP_RUNTIME/usr/lib/$ARCH/libexec/kf6"
+
+# Add path to VLC plugins
+export VLC_PLUGIN_PATH="$SNAP_DESKTOP_RUNTIME/usr/lib/$ARCH/vlc/plugins"
 ###########################################################
 # Mark update and exec binary
 # This is not used with the gnome extension for
